---
- hosts: localhost
  become_user: '{{ lookup("env", "USER") }}'
  vars:
    - user: "{{ lookup('env', 'USER') }}"
    - dotfiles_repo: 'git@github.com:ceramey1997/dotfiles.git'
    - ssh_key: '.ssh/id_rsa'

  tasks:
    - name: "Install system packages"
      apt:
        name:
          - bat
          - exa
          - jq
          - git
        state: latest

    - name: "Install asdf"
      script: /$HOME/.dotfiles/machine_setup/setup/asdf.sh



