---
- hosts: localhost
  become_user: '{{ lookup("env", "USER") }}'
  vars:
    - user: "{{ lookup('env', 'USER') }}"
    - dotfiles_repo: 'git@github.com:ceramey1997/dotfiles.git'
    - ssh_key: '.ssh/id_rsa'

  tasks:
    - name: "Install system packages"
      apt:
        name:
          - bat
          - exa
          - jq
          - git
        state: latest
    - name: "whoami"
      shell:
        cmd: |
          export ME={{ user }}
          echo $ME
        register: result

    - name: show result
      debug:
        var: result.stdout

    - name: "Install asdf"
      script: /$HOME/.dotfiles/machine_setup/setup/asdf.sh

    - name: "Install brew"
      script: /$HOME/.dotfiles/machine_setup/setup/brew.sh

    - name: "Install brew"
      script: /$HOME/.dotfiles/machine_setup/setup/brew.sh

    - name: "Install nvim"
      script: /$HOME/.dotfiles/machine_setup/setup/nvim.sh

    - name: "Install oh-my-posh"
      script: /$HOME/.dotfiles/machine_setup/setup/oh_my_posh.sh

    - name: "Install lazygit"
      script: /$HOME/.dotfiles/machine_setup/setup/lazygit.sh


